version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: first_app_container
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    networks:
      default:
      api_network:
        ipv4_address: 172.21.0.5
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - first_app_data:/var/lib/postgresql/data
    networks:
      - default
volumes:
  first_app_data:
networks:
  api_network:
    name: custom_api
    driver: bridge
  default:
    name: first_app_default
    driver: bridge