Book.create(name: 'Livro 1', author: 'Autor X', price: 12, discount: 1)
Book.create(name: 'Livro 2', author: 'Autor Y', price: 22, discount: 2)
Book.create(name: 'Livro 3', author: 'Autor Z', price: 31, discount: 1.3)
Client.create(email: 'cliente1@gmail.com', password: 'abc123')
Client.create(email: 'cliente2@gmail.com', password: 'abc123')